// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jumata96/pac-ent/ent/asistencia"
	"github.com/jumata96/pac-ent/ent/predicate"
)

// AsistenciaDelete is the builder for deleting a Asistencia entity.
type AsistenciaDelete struct {
	config
	hooks    []Hook
	mutation *AsistenciaMutation
}

// Where appends a list predicates to the AsistenciaDelete builder.
func (ad *AsistenciaDelete) Where(ps ...predicate.Asistencia) *AsistenciaDelete {
	ad.mutation.Where(ps...)
	return ad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ad *AsistenciaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ad.sqlExec, ad.mutation, ad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ad *AsistenciaDelete) ExecX(ctx context.Context) int {
	n, err := ad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ad *AsistenciaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(asistencia.Table, sqlgraph.NewFieldSpec(asistencia.FieldID, field.TypeInt))
	if ps := ad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ad.mutation.done = true
	return affected, err
}

// AsistenciaDeleteOne is the builder for deleting a single Asistencia entity.
type AsistenciaDeleteOne struct {
	ad *AsistenciaDelete
}

// Where appends a list predicates to the AsistenciaDelete builder.
func (ado *AsistenciaDeleteOne) Where(ps ...predicate.Asistencia) *AsistenciaDeleteOne {
	ado.ad.mutation.Where(ps...)
	return ado
}

// Exec executes the deletion query.
func (ado *AsistenciaDeleteOne) Exec(ctx context.Context) error {
	n, err := ado.ad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{asistencia.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ado *AsistenciaDeleteOne) ExecX(ctx context.Context) {
	if err := ado.Exec(ctx); err != nil {
		panic(err)
	}
}
