// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jumata96/pac-ent/ent/asistencia"
	"github.com/jumata96/pac-ent/ent/predicate"
)

// AsistenciaUpdate is the builder for updating Asistencia entities.
type AsistenciaUpdate struct {
	config
	hooks    []Hook
	mutation *AsistenciaMutation
}

// Where appends a list predicates to the AsistenciaUpdate builder.
func (au *AsistenciaUpdate) Where(ps ...predicate.Asistencia) *AsistenciaUpdate {
	au.mutation.Where(ps...)
	return au
}

// Mutation returns the AsistenciaMutation object of the builder.
func (au *AsistenciaUpdate) Mutation() *AsistenciaMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AsistenciaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AsistenciaUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AsistenciaUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AsistenciaUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AsistenciaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(asistencia.Table, asistencia.Columns, sqlgraph.NewFieldSpec(asistencia.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asistencia.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AsistenciaUpdateOne is the builder for updating a single Asistencia entity.
type AsistenciaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AsistenciaMutation
}

// Mutation returns the AsistenciaMutation object of the builder.
func (auo *AsistenciaUpdateOne) Mutation() *AsistenciaMutation {
	return auo.mutation
}

// Where appends a list predicates to the AsistenciaUpdate builder.
func (auo *AsistenciaUpdateOne) Where(ps ...predicate.Asistencia) *AsistenciaUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AsistenciaUpdateOne) Select(field string, fields ...string) *AsistenciaUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Asistencia entity.
func (auo *AsistenciaUpdateOne) Save(ctx context.Context) (*Asistencia, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AsistenciaUpdateOne) SaveX(ctx context.Context) *Asistencia {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AsistenciaUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AsistenciaUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AsistenciaUpdateOne) sqlSave(ctx context.Context) (_node *Asistencia, err error) {
	_spec := sqlgraph.NewUpdateSpec(asistencia.Table, asistencia.Columns, sqlgraph.NewFieldSpec(asistencia.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Asistencia.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asistencia.FieldID)
		for _, f := range fields {
			if !asistencia.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != asistencia.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &Asistencia{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asistencia.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
